import Head from "next/head";
import { Col, Row } from "reactstrap";
import SalesChart from "../pannel/components/dashboard/SalesChart";
import CustomerComponent from "../pannel/components/dashboard/CustomerComponent";
import TodayOverview from "../pannel/components/dashboard/TodayOverview";
import TopCards from "../pannel/components/dashboard/TopCards";
import SupplierComponent from "../pannel/components/dashboard/Supplier";
import ProductsComponent from "@/pannel/components/dashboard/Products";
import mongoose from "mongoose";
import Product from '../../models/Product';
import Contact from "../../models/Contact";


export default function Home({customer, product, supplier}) {

  const noOfCustomers = customer.length;
  const noOfProducts = product.length;
  const noOfSuppliers = supplier.length;
  

  return (
    <>
      <Head>
        <title>ERP System</title>
        <meta name="description" content="Generated by erp system" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div>
        {/***Top Cards***/}
        <Row>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-success text-success"
              href='/pannel/businessSetup/contactList'
              title="Customer"
              subtitle="Total Customer"
              amount={noOfCustomers}
              icon="bi bi-people"
            />
          </Col>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-danger text-danger"
              href='/pannel/businessSetup/productAndServices'
              title="Products"
              subtitle="Total Products"
              amount={noOfProducts}
              icon="bi bi-bag"
            />
          </Col>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-warning text-warning"
              href='/pannel/businessSetup/contactList'
              title="Supplier"
              subtitle="Total Supplier"
              amount={noOfSuppliers}
              icon="bi bi-basket3"
            />
          </Col>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-info text-into"
              href='/pannel/manageJournalEntries'
              title="Sales"
              subtitle="Total Sales"
              amount="$210"
              icon="bi bi-bag"
            />
          </Col>
        </Row>
        {/***Sales & Feed***/}
        <Row>
          <Col sm="12" lg="12">
            <SalesChart />
          </Col>
        </Row>

        {/***Table ***/}
        <Row>
          <Col lg="6" xxl="8" sm="12">
            <CustomerComponent />
          </Col>
          <Col lg="6" xxl="8" sm="12">
            <ProductsComponent />  
          </Col>
        </Row>

        <Row>
          <Col lg="6" xxl="8" sm="12">
            <SupplierComponent />
          </Col>
          <Col lg="6" xxl="8" sm="12">
          <TodayOverview />
          </Col>
        </Row>


      </div>
      </main>
    </>
  )
}


export async function getServerSideProps() {
  if (!mongoose.connections[0].readyState){
    mongoose.set("strictQuery", false);
    await mongoose.connect(process.env.MONGO_URI)
  }
  let customer = await Contact.find({"type": "Customer"})
  let supplier = await Contact.find({"type": "Supplier"})
  let product = await Product.find()
   
  // Pass data to the page via props
  return {
     props: {
      customer: JSON.parse(JSON.stringify(customer)),
      product: JSON.parse(JSON.stringify(product)),
      supplier: JSON.parse(JSON.stringify(supplier))
     }
     
    }
}